/** shared loading placeholders; all generated by AI coming from daisy ui docs */

export function ProductPageSkeleton() {
  return (
    <div className="grid gap-10 md:grid-cols-2">
      <div className="skeleton aspect-square w-full rounded-box" />
      <div className="space-y-4">
        <div className="skeleton h-8 w-3/4" />
        <div className="skeleton h-12 w-1/2" />
        <div className="skeleton h-40 w-full" />
      </div>
    </div>
  );
}

export function CartSkeleton({ lines = 3 }) {
  const n = Math.min(Math.max(lines, 1), 8);
  return (
    <div className="grid gap-10 lg:grid-cols-[1fr_320px]">
      <ul className="space-y-4">
        {Array.from({ length: n }).map((_, i) => (
          <li key={i} className="card card-side border border-base-300 bg-base-100 shadow-sm">
            <div className="p-4">
              <div className="skeleton h-24 w-24 rounded-box" />
            </div>
            <div className="card-body min-w-0 flex-row flex-wrap items-center justify-between gap-4">
              <div className="min-w-0 flex-1 space-y-3">
                <div className="skeleton h-6 w-48 max-w-full" />
                <div className="skeleton h-4 w-28" />
                <div className="flex flex-wrap items-center gap-3">
                  <div className="skeleton h-8 w-28" />
                  <div className="skeleton h-6 w-16" />
                </div>
              </div>
              <div className="skeleton h-6 w-20" />
            </div>
          </li>
        ))}
      </ul>
      <aside className="card border border-base-300 bg-base-100 p-6 shadow-md">
        <div className="flex justify-between gap-4">
          <div className="skeleton h-4 w-20" />
          <div className="skeleton h-4 w-24" />
        </div>
        <div className="skeleton mt-6 h-12 w-full rounded-lg" />
        <div className="skeleton mt-4 h-10 w-full" />
      </aside>
    </div>
  );
}

export function OrdersListSkeleton() {
  return (
    <div className="space-y-4">
      {[1, 2, 3, 4].map((i) => (
        <div key={i} className="card border border-base-300 bg-base-100 shadow-sm">
          <div className="card-body flex-row flex-wrap items-center gap-4 py-5 sm:gap-5">
            <div className="skeleton size-22 shrink-0 rounded-2xl" />
            <div className="min-w-0 flex-1 space-y-3">
              <div className="skeleton h-5 w-40" />
              <div className="skeleton h-4 w-56 max-w-full" />
              <div className="flex flex-wrap items-center gap-2">
                <div className="skeleton h-6 w-20 rounded-full" />
                <div className="skeleton h-4 w-24" />
              </div>
            </div>
            <div className="skeleton h-8 w-24 shrink-0" />
          </div>
        </div>
      ))}
    </div>
  );
}

export function AdminProductsTableSkeleton() {
  return (
    <div className="overflow-x-auto rounded-box border border-base-300 bg-base-100">
      <table className="table">
        <thead>
          <tr>
            {[1, 2, 3, 4, 5, 6, 7].map((i) => (
              <th key={i} className={i === 1 ? "w-24" : undefined}>
                <div className={`skeleton ${i === 1 ? "h-4 w-14" : "h-4 w-16"}`} />
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {[1, 2, 3, 4, 5, 6].map((row) => (
            <tr key={row}>
              <td>
                <div className="skeleton mx-auto h-14 w-14 shrink-0 rounded-xl sm:h-18 sm:w-18" />
              </td>
              {[2, 3, 4, 5, 6, 7].map((col) => (
                <td key={col}>
                  <div className="skeleton h-5 w-full max-w-32" />
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export function OrderDetailSkeleton() {
  return (
    <div className="space-y-8 text-left">
      <div className="skeleton h-9 w-40" />
      <div className="overflow-hidden rounded-2xl border border-base-300 bg-base-100 shadow-lg">
        <div className="bg-base-200/50 px-5 py-6 sm:px-8 sm:py-8">
          <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
            <div className="space-y-3">
              <div className="skeleton h-4 w-28" />
              <div className="skeleton h-9 w-48 max-w-full" />
              <div className="skeleton h-4 w-64 max-w-full" />
              <div className="skeleton h-3 w-full max-w-md" />
            </div>
            <div className="space-y-3 border-t border-base-300/80 pt-4 lg:border-t-0 lg:pt-0 lg:text-right">
              <div className="skeleton h-8 w-20 rounded-full lg:ml-auto" />
              <div className="skeleton h-10 w-32 lg:ml-auto" />
            </div>
          </div>
        </div>
        <div className="border-t border-base-300 px-5 py-4 sm:px-8">
          <div className="skeleton h-4 w-full max-w-2xl" />
          <div className="skeleton mt-2 h-4 w-full max-w-xl" />
        </div>
      </div>
      <div className="skeleton h-10 w-full max-w-md rounded-lg" />
      <div className="skeleton h-64 w-full rounded-2xl" />
    </div>
  );
}

export function OrderVideoSkeleton() {
  return (
    <div className="space-y-4">
      <div className="skeleton h-10 w-40" />
      <div className="skeleton min-h-[50vh] w-full rounded-box" />
    </div>
  );
}

export function OrderChatPanelSkeleton() {
  return (
    <div className="space-y-4">
      <div className="card border border-base-300 bg-base-100 shadow-sm">
        <div className="card-body flex-row flex-wrap items-start gap-4">
          <div className="skeleton h-12 w-12 shrink-0 rounded-box" />
          <div className="min-w-0 flex-1 space-y-2">
            <div className="skeleton h-6 w-48" />
            <div className="skeleton h-4 w-full max-w-lg" />
            <div className="skeleton h-4 w-2/3 max-w-md" />
          </div>
        </div>
      </div>
      <div className="flex h-[560px] flex-col overflow-hidden rounded-box border border-base-300 bg-base-100">
        <div className="border-b border-base-300 p-4">
          <div className="skeleton h-8 w-56" />
        </div>
        <div className="flex flex-1 flex-col gap-3 p-4">
          <div className="skeleton h-16 w-3/4 max-w-md rounded-lg" />
          <div className="skeleton ml-auto h-14 w-2/3 max-w-sm rounded-lg" />
          <div className="skeleton h-20 w-4/5 max-w-lg rounded-lg" />
        </div>
        <div className="border-t border-base-300 p-3">
          <div className="skeleton h-10 w-full rounded-lg" />
        </div>
      </div>
    </div>
  );
}